import path from "path";
import fs from "fs-extra";

export async function generateIgnoreFile(rootPath: string) {
    const ignoreFilePath = path.join(rootPath, '.lbbign');
    await fs.writeFile(ignoreFilePath, '// Generated by @libria/ts-barrels', 'utf-8');
}